image: centos:latest

before_script:
  - yum -y install git epel-release "@Development Tools"
  - yum -y install createrepo mock redhat-rpm-config rpmdevtools
  - yum -y install openssl openssl-devel bc

pages:
  script:
  - cat /etc/redhat-release
  - mkdir public
  - curl https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.5.5.tar.xz -o linux.tar.xz
  - tar -xJf linux.tar.xz
  - mv linux-4.5.5 linux
  - cp config linux/.config
  - cd linux
  - make olddefconfig
  - make rpm
  artifacts:
    paths:
    - public
  only:
  - master
